### ISSUE TITLE
Unexpected className found parsing DocumentLocation Xcode3ProjectDocumentLocation

### ISSUE THREAD

**Issue by zhangrenfeng** [spotify/XCLogParser#39] opened 2019-11-04 03:59 UTC
Hello,

I'm trying to run `xclogparser` after a build and am getting this error:
`Error parsing the log: Unexpected className found parsing DocumentLocation Xcode3ProjectDocumentLocation`

I'm running on `Xcode Version 11.2 (11B52)`

Sorry, I can't provide log file because the logs involve sensitive information..

**Comment by BalestraPatrick** [comment] 2019-11-04 12:02
This is a duplicate of #36 and it's fixed in #38

**Comment by ecamacho** [comment] 2019-11-04 18:45
I think it's different, that `Xcode3ProjectDocumentLocation` seems to be in a different Xcode framework. I'm reopening to do some research

**Comment by ecamacho** [comment] 2019-11-04 19:07
@zhangrenfeng it's hard to test without a log, but can you try this version and let me know if it works?  [XCLogParser-Experimental.zip](https://github.com/spotify/XCLogParser/files/3805604/XCLogParser-Experimental.zip)

**Comment by zhangrenfeng** [comment] 2019-11-05 03:04
> @zhangrenfeng it's hard to test without a log, but can you try this version and let me know if it works? [XCLogParser-Experimental.zip](https://github.com/spotify/XCLogParser/files/3805604/XCLogParser-Experimental.zip)

I use the command line tool you provided to parse the same xcactivitylog file, and the file can be parsed correctly without error

**Comment by ecamacho** [comment] 2019-11-05 08:19
@zhangrenfeng great, I opened a PR to merge the fix to master https://github.com/spotify/XCLogParser/pull/40

**Closed** 2019-11-08 09:54 UTC
